LIMIT_BOTTOM = 40
LIMIT_TOP = 5
LIMIT_L =  5
LIMIT_R = 170
SKY = 3
HEIGHT = LIMIT_BOTTOM - LIMIT_TOP
WIDTH = LIMIT_R - LIMIT_L
PLAYER_INIT = (2, HEIGHT - 1) 
GRAVITY = 1
VELX = 2
VELY = -3
MANDO_SPRITE = ''' 0 __
C D -
C D  
I I   '''
COIN = '''$'''
BEAM1 = '''_______'''
BEAM2 = '''|
|
|
|'''
BEAM3 = '''\\
 \\
  \\
   \\'''
PEW = '--'
PEW_VEL = 3
LIVES = 5
# PEW_VEL = 3
# FORE = ['BLACK', 'RED', 'GREEN', 'YELLOW', 'BLUE', 'MAGENTA', 'CYAN', 'WHITE', 'RESET']
# BACK = ['BLACK', 'RED', 'GREEN', 'YELLOW', 'BLUE', 'MAGENTA', 'CYAN', 'WHITE', 'RESET']
# STYLE =  ['DIM', 'NORMAL', 'BRIGHT', 'RESET_ALL']