LIMIT_BOTTOM = 43
LIMIT_TOP = 2
LIMIT_L =  5
LIMIT_R = 170
SKY = 3
HEIGHT = LIMIT_BOTTOM - LIMIT_TOP
WIDTH = LIMIT_R - LIMIT_L
PLAYER_INIT = (2, HEIGHT - 1) 
GRAVITY = 1
VELX = 2
MAX_VELY = 3
MAX_VELX = 3
MIN_VELY = -3
MIN_VELX = -3
ACCY = 3
ACCX = 3
MANDO_SPRITE = ''' 0 __
C D -
C D  
I I   '''
MANDO_SHIELD = '''| 0 __|
|C D -|
|C D  |
|I I  | '''
COIN = '''$'''
BEAM1 = '''_______'''
BEAM2 = '''|
|
|
|'''
BEAM3 = '''\\
 \\
  \\
   \\'''
PEW = '--'
MAGNET = '|M|'
SPEEDUP = '|S|'
MAG_FORCE = 1
MAG_RANGE_X = 40
MAG_RANGE_Y = 30
PEW_VEL = 3
LIVES = 5
TFP = 0.1
SHIELD_TIME = 10
# PEW_VEL = 3
# FORE = ['BLACK', 'RED', 'GREEN', 'YELLOW', 'BLUE', 'MAGENTA', 'CYAN', 'WHITE', 'RESET']
# BACK = ['BLACK', 'RED', 'GREEN', 'YELLOW', 'BLUE', 'MAGENTA', 'CYAN', 'WHITE', 'RESET']
# STYLE =  ['DIM', 'NORMAL', 'BRIGHT', 'RESET_ALL']